force-app/main/default/objects/YouTube_Search_Request__c/YouTube_Search_Request__c.object-meta.xml
<CustomObject>
    <description>This object will trigger the integration.</description>
    <label>YouTube Search Request</label>
    <nameField>
        <label>YouTube Search Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YouTube Search Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YouTube_Search_Request__c/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <label>Keyword</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YouTube_Video__c/YouTube_Video__c.object-meta.xml
<CustomObject>
    <description>Store Youtube Data</description>
    <label>YouTube Video</label>
    <nameField>
        <label>YouTube Video</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YouTube Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YouTube_Video__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <label>Channel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YouTube_Video__c/fields/Video_Id__c.field-meta.xml
<CustomField>
    <fullName>Video_Id__c</fullName>
    <externalId>true</externalId>
    <label>Video Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YouTubeQueueable.cls
public class YouTubeQueueable implements Queueable, Database.AllowsCallouts {

    private List<Id> requestIds;

    public YouTubeQueueable(List<Id> requestIds){
        this.requestIds = requestIds;
    }

    public void execute(QueueableContext context){

        List<YouTube_Search_Request__c> requests =
        [SELECT Id, Keyword__c
         FROM YouTube_Search_Request__c
         WHERE Id IN :requestIds];

        for(YouTube_Search_Request__c req : requests){

            String response = YouTubeService.searchVideos(req.Keyword__c);

            YouTubeWrapper data =
            (YouTubeWrapper)JSON.deserialize(response, YouTubeWrapper.class);

            List<YouTube_Video__c> videos = new List<YouTube_Video__c>();

            for(YouTubeWrapper.Item item : data.items){

                YouTube_Video__c video = new YouTube_Video__c();

                video.Video_Id__c = item.id.videoId;
                video.Title__c = item.snippet.title;
                video.Channel_Name__c = item.snippet.channelTitle;
                video.Description__c = item.snippet.description;
                //video.Thumbnail_URL__c = item.snippet.thumbnails.defaultThumbnail.url;

                videos.add(video);

            }

            if(!videos.isEmpty()){
                upsert videos Video_Id__c;
            }

        }

    }

}